### ISSUE TITLE
Input data directly for visualization in the nature paper

### ISSUE THREAD

**Issue by JaysonChao** [surh/pbi#1]
hi, I have downloaded data from the paper website, which was origin data. I want to reproduce your figures in the paper. Is that ok you upload data preprocessed directly for data visualization? For example data you mentioned in the code "~/rhizogenomics/data/phosphate/census/data/otu_table.txt" cannot be found in the supplemental data.

**Comment by surh** [comment]
Hi Jayson,

Thanks for your interest. The data is available as part of the supplementary information files of the paper.

Unfortunately, we had to provide those files as excel tables for the journal.

The OTU table of the census is in the first tab (named counts) of the "Supplementary Dataset 1" excel file that you can obtain [here](https://www.nature.com/nature/journal/v543/n7646/full/nature21417.html#supplementary-information) as a zip file together with other files.

There is a pdf named "Supplementary_Table_and_Data_guide" that describes what is on each file.

Sorry for the inconvenience, and let me know if you can't find it.

Sur

**Comment by JaysonChao** [comment]
Thank you very much. I spent some time arranging your data for further manipulation and visualization. Your code is gorgeous. I am also interested in writing my own package for data analysis and visualization. I am wondering if that is ok you share some experience with me about details in plotting. I love your style of barplot function phyloggram()

**Comment by surh** [comment]
Glad it worked, and that you like the plots!

I'm happy to answer any other specific questions. If they are about functions in AMOR, please direct them to the issues section of that repo (https://github.com/surh/AMOR/issues).

Sur
