### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by EnvGenomics** [surh/pbi#2]
Hi, I am currently reproduce your figure in the Nature paper. What I found confused is that not all the data your mentioned in the r code were available. For example, the "weighted_unifrac_otu_table_filter_rar1000.txt" cannot be found anywhere in the repository or calculated in other code .Is that ok you check all of your code and data availability and upload a full data list?

Thank you very much

**Comment by surh** [comment]
Hi,

Thank you for your interest. I have uploaded the UniFrac distance matrices to the newly created misc directory in the repository.

Please note that those files are very specific for the dataset published in [Castrillo *et al*. 2017](http://www.nature.com/doifinder/10.1038/nature21417). If you intend to use the code here as basis for analysis for a different dataset you would need to calculate UniFrac distances in that dataset.

Also note that all the data for calculating UniFrac distances is all available as part of the [supplementary material](https://www.nature.com/nature/journal/v543/n7646/full/nature21417.html#supplementary-information). We use a third party software (QIIME) to calculate UniFrac, so there is no reason to duplicate their code here.

Please let me know if you think some other information is missing.

Thanks,
Sur
